### PR TITLE
WIP: add human readable output flag

### LINKED ISSUE #18: Human Readable Output
The raw JSON results are useful, but they can be difficult to read:
```sh
web3-cli bl
{
  "parentHash": "0x011037ae37b32b148ab52442fe77ad01e2e7c1fbe9dc2d842c455eca63d446f1",
  "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  "miner": "0x1ee4baf2cccc633b8e2c06a3ac20319610cf3cd5",
  "signers": [],
  "voters": [],
  "signer": "0x52eac2ab9a8d5d342051dd6e53771d43b31f4604b89a113542fdefcf16689b2b60d3e07a176e80e61a5a661156519c16b54dd9df699bee766b9b1dfd394d7ccd00",
  "stateRoot": "0x9427b1737dcb5ba6c4a46c139fcacdb74d05464eddb2e8ba656a7526ad719790",
  "transactionsRoot": "0xaf71bf06348ca6d7b1fc6898eb856edab74fe0ba5cefb221e80d76f4d4fc3a67",
  "receiptsRoot": "0xcfad9c26ff4b1c03ec6fe24dc6766624fadb92641b900c07b90ba5559f59ba5c",
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "difficulty": "0x11",
  "number": "0x40d0f7",
  "gasLimit": "0x822d320",
  "gasUsed": "0x4ce78",
  "timestamp": "0x5c3f9d80",
  "extraData": "0x322e322e372f6c696e75782d616d6436342f676f312e31312e31000000000000",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "nonce": "0x0000000000000000",
  "hash": "0x0029f167fa0b1af69c74a28a38b5f966fb295b15394dc3188b8c494d9b9ea0f8"
}
```
We should support human readable output (hex->decimal integer, hex->timestamp, hex->utf8):
```sh
web3-cli -human bl
{
  "parentHash": "0x8227a2c53fe9cdfd5ee9140dc396d01d2b8ad694b7bb3a5e845c687f38f29500",
  "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  "miner": "0xe1200caf0d92018fe111943faf91a0c5f6db34d1",
  "signers": [],
  "voters": [],
  "signer": "0x3343e97b758bd5b9a09917fcebf2b31a08c3bd824cfb2839f0bbab79f64708722b533b3c9d59362417cead66e6914595b7a87e547bc908f500b4e812226fd82f00",
  "stateRoot": "0xf80efc7529e9c0210e1a4b43fcce6c175066e967558edb18458e6b81f22434e2",
  "transactionsRoot": "0x84744e1ce155074d50dcc22f2a94d6980e65ccc514d390eb280d2661dd3648ff",
  "receiptsRoot": "0x056b23fbba480696b65fe5a59b8f2148a1299103c4f57df839233af2cf4ca2d2",
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "difficulty": 17,
  "number": 4248553,
  "gasLimit": 136500000,
  "gasUsed": 21000,
  "timestamp": "2019-01-16T16:12:10-06:00",
  "extraData": "2.1.36/linux-amd64/go1.10.3\u0000\u0000\u0000\u0000\u0000",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "nonce": "0x0000000000000000",
  "hash": "0x51afe20f0ac82251d00ef165ede160349f5b3218269d013245565bd30860ad20"
}
```

```sh
web3-cli bl | jq .difficulty
"0x11"
web3-cli -human bl | jq .difficulty
17
```
Either (1) this output should be behind a new flag (`-human`? `-pretty`?), or (2) this should be the default output with the original raw fields behind a flag (`-raw`?). I'm leaning towards (2).

### PR DESCRIPTION
**Pull request by jmank88**
This PR adds human readable output. Fixes #18.

It is currently behind the `-human` flag, but perhaps should become the default, with the raw JSON fields behind some other flag.

- [ ] default to human - add `-format json`

### CODE REVIEW

**Comment by treeder** [comment]
ya, let's flip it, make it human readable by default. And perhaps a `--format json`, rather than an ambiguous top level flag (also lets us add other formats).

**Comment by jmank88** [comment]
Should we abandon JSON entirely on the human readable side? e.g.
```sh
Field1: This is text
Field2: 12345
```
rather than:
```sh
{
  "Field1": "This is text",
  "Field2": 12345
}
```

**Comment by jmank88** [comment]
Here is an example for readable block output:
```sh
web3-cli bl
Number: 4263633
Time: 2019-01-17T19:08:50Z
Transactions: 26
Gas Used: 546000/136500000 (0.40%)
Difficulty: 17
Hash: 0xcae2a1d5a7ee9d5f63ace79611d03eba5739c9bbf0024a54355b1c59687dfcfa
Vanity: GoChain 1
Coinbase: 0xEd7F2e81B0264177e0df8f275f97Fd74Fa51A896
ParentHash: 0xb9d7168ea2d9c2241335bc9d1b0c53377ee191e1a1ef156fdb1c01355af90d44
UncleHash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
Nonce: 0
Root: 0x07c03d7010398ac554c9fe896b9d75de5858665e0a760132e46c228907d04643
TxHash: 0x6a93f2f54388e9cf7044387b417ce34620607f2037cf05ca09a3c1f12e609f4f
ReceiptHash: 0x5066de2f28c5b87680a3b2f4d7095cb89aacf730bb9e00bf95c208776d85753a
Bloom: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
MixDigest: 0x0000000000000000000000000000000000000000000000000000000000000000
Signer: 0xb4a5152309b8a750b06626c54ee9dffbe74dfac1edabf2c9cac4f10ed931a6b53f731d1a0686ec61270da0ae0b07515bdce80da7a45267334cfc16633a4ab38f01
```
and
```sh
web3-cli -network ethereum bl
Number: 7083071
Time: 2019-01-17T19:07:44Z
Transactions: 69
Gas Used: 7632693/8000029 (95.41%)
Difficulty: 2587438214140767
Hash: 0x59310af4c220f7a41e1464b7321afb08010e5cb101196d1b6ea0255a33acec8f
Vanity: nanopool.org
Coinbase: 0x52bc44d5378309EE2abF1539BF71dE1b7d7bE3b5
ParentHash: 0x55a605bb7ae9bf4c454fb36a1c926bfc6d08e85df88cc37994568d0c7fbf6c4b
UncleHash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
Nonce: 15990024808061077333
Root: 0xbaf60a4fd98c91e3c79a6c80f444aea6b386972da9aed818ef70f6047fe58a6d
TxHash: 0x8f11f6191136c16f1fab8685b75d310eff701feb1c6e98bceb926eaefdc55852
ReceiptHash: 0xb33b129a65bd4990de6df4d5246b5e300a66baf338e57441436581695bd5355c
Bloom: 0x8000040a0406403a20680401cc0200028426000c0140240c301114700220ee69198238100c05424303d82434480408004200020008258101c02190e060380012840010c5ad41802152941029001000807e084604994000000b0208048844442b0b25822002e31411926001508002280154013f2000942420100004737010210504e14230002588c2860484c453240c59084000c18188880c480504a9200005500a0c0ce9006021061003120c12208000640460008200a04600b4c1213f08010050400802808089049588100a1608160088680505800c53012c1600de0842a020781071281001408400822802444aa0894000002228000051005a20c902e000b5
MixDigest: 0x1ce2f9f348fdce74a0dc9fce803e2c9ab07835ef849a7fb1892ad32cb315548f
```

**Comment by jmank88** [comment]
Updated to default to human readable, and moved json behind a `format` flag.

**Pull request merged**
